version: 0.2

env:
  shell: bash
  parameter-store:
    FRONTEND_BUCKET: FRONTEND_BUCKET
    FRONTEND_DISTRIBUTION: FRONTEND_DISTRIBUTION

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - aws --version
      - python --version
      - echo "Installing poetry..."
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - node --version
      - npm --version
      - echo "Installing yarn..."
      - npm install -g yarn
  pre_build:
    commands:
      - source $HOME/.poetry/env
      - make venv
      - make lint
      - make typecheck
      - make test
  build:
    commands:
      - make node_modules
      - make deploy
