version: 0.2

env:
  shell: bash
  parameter-store:
    REACT_APP_BACKEND_URL: REACT_APP_BACKEND_URL
    FRONTEND_BUCKET: FRONTEND_BUCKET
    FRONTEND_DISTRIBUTION: FRONTEND_DISTRIBUTION

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - aws --version
      - node --version
      - npm --version
      - echo "Installing yarn..."
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - make -C frontend deploy
