service: us-covid-stats

configValidationMode: error

custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
    slim: true
  cfResources: ${file(./cloudformation.yml):Resources}
  cfOutputs: ${file(./cloudformation.yml):Outputs}
  subscriptionEnabled: ${env:SUBSCRIPTION_ENABLED, 'no'}
  subscription:
    yes:
      - Endpoint: ${env:SUBSCRIPTION_EMAIL, ''}
        Protocol: email
    no: []

provider:
  name: aws
  runtime: python3.8
  stage: ${env:STAGE,'main'}
  region: ${env:AWS_REGION,'us-east-1'}
  logRetentionInDays: 1
  memorySize: 3008
  timeout: 20
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:BatchWriteItem
      Resource:
        - !GetAtt DataTable.Arn
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - !GetAtt DataBucket.Arn
        - !Join [ '/', [ !GetAtt DataBucket.Arn, '*' ]  ]
  environment:
    SERVICE_NAME: ${self:service}
    DATA_TABLE:
      Ref: DataTable
    DATA_BUCKET:
      Ref: DataBucket
  httpApi:
    payload: '2.0'
    cors: true
  tags:
    project: ${self:service}

plugins:
  - serverless-python-requirements

package:
  include:
    - '!**'
    - 'us_covid_stats/**'
  exclude:
    - '**/tests/**'
    - 'us_covid_stats/conftest.py'


functions:

  RefreshDataFromSources:
    handler: us_covid_stats/etl/handler.refresh_data_from_sources
    events:
      - schedule: rate(1 hour)
    destinations:
      onSuccess: OnRefreshSuccess
      onFailure: OnRefreshFailure
  OnRefreshSuccess:
    handler: us_covid_stats/etl/handler.on_refresh_success
  OnRefreshFailure:
    handler: us_covid_stats/etl/handler.on_refresh_failure
  GetData:
    handler: us_covid_stats/rest/handler.get_data
    events:
      - httpApi:
          method: GET
          path: /data
  GetWeekly:
    handler: us_covid_stats/rest/handler.get_weekly
    events:
      - httpApi:
          method: GET
          path: /weekly
  GetMonthly:
    handler: us_covid_stats/rest/handler.get_monthly
    events:
      - httpApi:
          method: GET
          path: /monthly

resources:
  Resources:
    ReactAppBackendUrlParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: REACT_APP_BACKEND_URL
        Type: String
        Value: !Join [ '', [ 'https://', !Ref HttpApi, '.execute-api.', !Ref 'AWS::Region', '.', !Ref 'AWS::URLSuffix' ] ]
    OnRefreshSuccessNotification:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Data refresh successful.
        Subscription: ${self:custom.subscription.${self:custom.subscriptionEnabled}}
    OnRefreshFailureNotification:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Data refresh failed.
    DataTable: ${self:custom.cfResources.DataTable}
    DataBucket: ${self:custom.cfResources.DataBucket}
    FrontendBucket: ${self:custom.cfResources.FrontendBucket}
    FrontendBucketPolicy: ${self:custom.cfResources.FrontendBucketPolicy}
    CloudFrontOriginAccessIdentity: ${self:custom.cfResources.CloudFrontOriginAccessIdentity}
    FrontendDistribution: ${self:custom.cfResources.FrontendDistribution}
    FrontendBucketParameter: ${self:custom.cfResources.FrontendBucketParameter}
    FrontendDistributionParameter: ${self:custom.cfResources.FrontendDistributionParameter}
  Outputs:
    DataBucketName: ${self:custom.cfOutputs.DataBucketName}
    FrontendBucketName: ${self:custom.cfOutputs.FrontBucketName}
    FrontendDistributionId: ${self:custom.cfOutputs.FrontendDistribution}
    FrontendUrl: ${self:custom.cfOutputs.FrontendUrl}
