name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.4

      - name: Setup Virtualenv Cache
        uses: actions/cache@v2.1.3
        id: virtualenv-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install Python Dependencies
        if: steps.virtualenv-cache.outputs.cache-hit != 'true'
        run: make venv

      - name: Lint with Flake8
        run: make flake8

      - name: Lint with Black
        run: make black_check

      - name: Checking type annotations
        run: make typecheck

      - name: Running tests
        run: make test

      - name: Set up Node 12.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up Yarn cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Set up node_modules cache
        uses: actions/cache@v2.1.3
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-backend
            ${{ runner.os }}-

      - name: Install Node dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: make node_modules

      - name: Set up Serverless cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/serverless-python-requirements
          key: ${{ runner.os }}-serverless-python-requirements-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-serverless-python-requirements
            ${{ runner.os }}-

      - name: Build serverless package
        run: make build
  Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.4

      - name: Set up Node 12.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up Yarn cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Set up node_modules cache
        uses: actions/cache@v2.1.3
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-frontend
            ${{ runner.os }}-

      - name: Install Node dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: make node_modules

      - name: Build frontend artifacts
        run: make build
  CloudFormation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Lint CloudFormation files
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: "**/cloudformation.yml"
